name: Deploy

on:
  workflow_dispatch:

env:
  ACR_REGISTRY: haleon.azurecr.cn
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Container Registry
        run: |
          docker login ${ACR_REGISTRY} \
          -u "haleon" \
          -p "${ACR_PASSWORD}"

      - name: Build Docker image
        run: |
          docker build -t ${ACR_REGISTRY}/react-app:latest .

      - name: Push Docker image
        run: |
          docker push ${ACR_REGISTRY}/react-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ env.KUBECONFIG_FILE }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Restart webhook-api deployment
        run: |
          kubectl rollout restart deployment webhook-api