name: Deploy to Kubernetes

on:
  push:
    branches: [ master ]

env:
  ACR_REGISTRY: haleon.azurecr.cn
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Container Registry
        run: |
          docker login ${ACR_REGISTRY} \
          -u "haleon" \
          -p "${ACR_PASSWORD}"

      - name: Build and push Docker image
        run: |
          docker build -t ${ACR_REGISTRY}/react-app:${{ github.sha }} .
          docker push ${ACR_REGISTRY}/react-app:${{ github.sha }}